server:
  port: 9090
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: EMPLOYEE-SERVICE
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/api/employee/**
        - id: EMPLOYEE-SERVICE
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/api/department/**
  config:
    import: configserver:http://localhost:9296