spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employeedb?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 12345678
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server:
  port: 8080
logging:
  file: logs/application.log
  pattern:
    console: '%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
